// Copyright 2020-2022 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is the generated code that matches the definition found in the
// bufimageutil_test files. This is a temporary file to demonstrate how a
// user would recover the option value associated with one of the nodes in
// a plugin.
//
// For details, see private/buf/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
//
// TODO: We might want to have some sort of 'unittest' Protobuf directory so that
// we have a standard place to generate definitions from test files.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: foo/foo.proto

package bufimageutiltesting

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Foo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
}

func (x *Foo) Reset() {
	*x = Foo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foo_foo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_foo_foo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_foo_foo_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_foo_foo_proto protoreflect.FileDescriptor

var file_foo_foo_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x6f, 0x6f, 0x2f, 0x66, 0x6f, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x66, 0x6f, 0x6f, 0x22, 0x27, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x17, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x71, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x42, 0x08, 0x46, 0x6f, 0x6f, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x75, 0x66, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6f, 0x2f, 0x66, 0x6f, 0x6f, 0xa2, 0x02, 0x03, 0x46, 0x58, 0x58, 0xaa, 0x02, 0x03, 0x46,
	0x6f, 0x6f, 0xca, 0x02, 0x03, 0x46, 0x6f, 0x6f, 0xe2, 0x02, 0x0f, 0x46, 0x6f, 0x6f, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x03, 0x46, 0x6f, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foo_foo_proto_rawDescOnce sync.Once
	file_foo_foo_proto_rawDescData = file_foo_foo_proto_rawDesc
)

func file_foo_foo_proto_rawDescGZIP() []byte {
	file_foo_foo_proto_rawDescOnce.Do(func() {
		file_foo_foo_proto_rawDescData = protoimpl.X.CompressGZIP(file_foo_foo_proto_rawDescData)
	})
	return file_foo_foo_proto_rawDescData
}

var file_foo_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_foo_foo_proto_goTypes = []interface{}{
	(*Foo)(nil), // 0: foo.Foo
}
var file_foo_foo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foo_foo_proto_init() }
func file_foo_foo_proto_init() {
	if File_foo_foo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foo_foo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Foo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_foo_foo_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foo_foo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foo_foo_proto_goTypes,
		DependencyIndexes: file_foo_foo_proto_depIdxs,
		MessageInfos:      file_foo_foo_proto_msgTypes,
	}.Build()
	File_foo_foo_proto = out.File
	file_foo_foo_proto_rawDesc = nil
	file_foo_foo_proto_goTypes = nil
	file_foo_foo_proto_depIdxs = nil
}
